export const SET_LIVE_ORDER_LIST = 'SET_LIVE_ORDER_LIST';
export const SET_LIVE_SELECT_ORDER = 'SET_LIVE_SELECT_ORDER';
export const SET_LIVE_SELECT_THREAD = 'SET_LIVE_SELECT_THREAD';

export const SET_LIVE_SELECT_TOKEN = 'SET_LIVE_SELECT_TOKEN';

export const SET_LIVE_OWN_MESSAGE = 'SET_LIVE_OWN_MESSAGE';

export const REMOVE_SELECT_DATA = 'REMOVE_SELECT_DATA';
