export const membersActionTypes = {
  SET_MEMBER_LIST: "SET_MEMBER_LIST",

  SET_MEMBER_INFO_BEGIN: "SET_MEMBER_INFO_BEGIN",
  SET_MEMBER_INFO_SUCCESS: "SET_MEMBER_INFO_SUCCESS",
  SET_MEMBER_INFO_ERROR: "SET_MEMBER_INFO_ERROR",
  CLEAN_MEMBER_INFO_STATUS: "CLEAN_MEMBER_INFO_STATUS",
};
