export const SET_MESSAGE_LIST = 'SET_MESSAGE_LIST';
export const SET_SELECT_THREAD = 'SET_SELECT_THREAD';
export const UPDATE_MESSAGE_LIST = 'UPDATE_MESSAGE_LIST';
export const REMOVE_SELECT_THREAD = 'REMOVE_SELECT_THREAD';

export const SET_UNREAD_MESSAGE_COUNT = 'SET_UNREAD_MESSAGE_COUNT';
export const REMOVE_UNREAD_ITEM = 'REMOVE_UNREAD_ITEM';
