export const memberChatActionTypes = {
  SET_MEMBER_CHAT_ONLINE: "[Member Chat]: SET_MEMBER_CHAT_ONLINE",
  SET_MEMBER_CHAT_USER: "[Member Chat]: SET_MEMBER_CHAT_USER",

  SET_MEMBER_CHAT_MESSAGE_LIST: "[Member Chat]: SET_MEMBER_CHAT_MESSAGE_LIST",
  SET_MEMBER_CHAT_MESSAGE: "[Member Chat]: SET_MEMBER_CHAT_MESSAGE",

  FETCH_USER_DETAIL_START: "[Member Chat]: FETCH_USER_DETAIL_START",
  FETCH_USER_DETAIL_SUCCESS: "[Member Chat]: FETCH_USER_DETAIL_SUCCESS",
  FETCH_USER_DETAIL_FAILED: "[Member Chat]: FETCH_USER_DETAIL_FAILED",
};
